# Detect OS
OS = $(shell uname -s)

# Defaults
ECHO = echo

# Make adjustments based on OS
ifneq (, $(findstring CYGWIN, $(OS)))
	OS_CYGWIN = "true"
	ECHO = /bin/echo -e
else ifneq (, $(findstring Linux, $(OS)))
	OS_LINUX = "true"
else ifneq (, $(findstring Darwin, $(OS)))
	OS_MAC = "true"
endif



# target: install                 - Install needed utilities locally.
.PHONY: install
install:

	install -d build
	install -d bin

	# Shellcheck
ifdef OS_LINUX
	curl -Ls https://github.com/koalaman/shellcheck/releases/download/latest/shellcheck-latest.linux.x86_64.tar.xz | tar -xJ -C build/ && rm -f bin/shellcheck && ln build/shellcheck-latest/shellcheck bin/
else ifdef OS_MAC
	curl -Ls https://github.com/koalaman/shellcheck/releases/download/latest/shellcheck-latest.darwin.x86_64.tar.xz | tar -xJ -C build/ && rm -f bin/shellcheck && ln build/shellcheck-latest/shellcheck bin/
endif



# target: clean                 - Clean installed utilities.
.PHONY: clean
clean:
	rm -rf bin build



# target: test                 - Execute tests.
.PHONY: test
test:
	# Shellcheck för sample/*.bash
	@for f in "sample/*.bash"; do  \
		printf " %s\n" $$f;        \
		bin/shellcheck $$f;        \
	done;
